spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 相关配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      # 基本属性
      url: jdbc:mysql://localhost:3306/chapter5?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
