spring:
  datasource:
    hikari:
      # 基本属性
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/chapter7?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456

  #热部署的配置
  devtools:
    restart:
      enabled: true
