spring:
  rabbitmq:
    username: guest    # 默认为`guest`
    password: guest    # 默认为`guest`
    host: localhost    # 默认为`localhost`
    port: 5672  # 默认为 5672
    virtual-host: /
    # 手动ACK，不开启自动ACK，目的是为了防止报错后未正确处理消息丢失，默认为`none`，不 ACK
    listener:
      simple:
        acknowledge-mode: manual
    # 启用发布服务器确认
    publisher-confirms: true
    # 启动发布服务器返回
    publisher-returns: true