spring:
  swagger:
    # 启动swagger，默认为 true
    enabled: true
    # 扫描的包路径,默认扫描所有
    base-package: com.fatal
    security:
      # true: 开启后访问 swagger-ui.html 会自动路由到登陆页面，保障接口信息不被暴露
      filter-plugin: true
      # 配置账号、密码
      username: fatal
      password: 123456
    contact:
      name: fatal
      url: fatal's url
      email: 634137063@qq.com
    # 描述
    description: Spring Boot2 集成Swagger2在线调试（battcn版）
    # 版本
    version: 1.0
