server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 基本属性 	allowMultiQueries：设置为true后，数据库那边才允许你批量更新。编码属性设置了存储数据到数据库才不会是乱码
    url: jdbc:mysql://localhost:3306/chapter11?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 注意：一定要对应 mapper 映射xml文件的所在路径
  type-aliases-package: com.fatal.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 可以自控制台上输出 sql 语句