spring:
  mail:
    default-encoding: utf-8
    # SMTP server host. For instance, `smtp.example.com`.
    host: smtp.qq.com
    # 账号
    username: xxx@qq.com
    # 密码（授权码）
    password: xxxxxxxxxxxxxx
    # 协议默认为 SMTP
    protocol: smtp