spring:
  mail:
    default-encoding: utf-8
    # SMTP server host. For instance, `smtp.example.com`.
    host: smtp.qq.com
    # \u8D26\u53F7
    username: 634137063@qq.com
    # \u5BC6\u7801\uFF08\u6388\u6743\u7801\uFF09
    password: gdhzdpvlcuvxbcgj
    # \u534F\u8BAE\u9ED8\u8BA4\u4E3A SMTP
    protocol: smtp
