spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 相关配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      # 基本属性
      url: jdbc:mysql://localhost:3306/chapter24_3?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
  jpa:
    # 显示 sql
    show-sql: true
    # 数据库类型
    database: mysql
    # JPA 配置
    hibernate:
      #  update：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
      ddl-auto: update
    # 指定生成的表的引擎为InnoDB类型（默认是MyISAM，MyISAM不支持事务）
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect