spring:
  redis:
    host: localhost
    password: 123456
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 1
    # 连接超时时间
    timeout: 10000ms

# 把这里边用到的API解释下，然后将整合篇做笔记。整合完毕后，再次复习下redis，回头来做详情篇
# 还有学习 spring-data-redis